[project]
name = "diplomacy-edu-chatbot-api"
version = "1.0.0"
description = "Public Chatbot API for Diplomacy Edu Website Chatbot"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "apscheduler (>=3.11.0,<4.0.0)",
    "mongoengine (>=0.29.1,<0.30.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "databases (>=0.9.0,<0.10.0)",
    "weaviate-client (>=4.12.0,<5.0.0)",
    "openai (>=1.70.0,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "langchain-weaviate (>=0.0.6,<0.1.0)",
    "langchain (>=0.3.23,<0.4.0)",
    "langchain-openai (>=0.3.12,<2.0.0)",
    "langchain-community (>=0.3.21,<1.0.0)",
    "langgraph[sqlite] (>=1.0.0,<2.0.0)",
    "langgraph-checkpoint-sqlite (>=2.0.6,<4.0.0)",
    "aiosqlite (>=0.21.0,<0.22.0)",
    "motor (>=3.7.0,<4.0.0)",
    "websockets (>=15.0.1,<16.0.0)",
    "langchain-anthropic (>=0.3.14,<2.0.0)",
    "redis (>=7.1.0,<8.0.0)",
    "neo4j (>=5.17.0,<6.0.0)",
    "langfuse (>=3.0.0,<4.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
